on:
  push:
    branches:
      - main

  pull_request:

jobs:
  test:
    runs-on: test-3
    steps:
    - uses: actions/checkout@v4
    - run: |
      mkdir build
      cd build
      cmake ..
      make -j
      I_MPI_OFFLOAD=0 mpirun -n 2  ./send-receive
      I_MPI_OFFLOAD=0 mpirun -n 2  ./put-get
      I_MPI_OFFLOAD=1 mpirun -n 2  ./send-receive device
      I_MPI_OFFLOAD=1 mpirun -n 2  ./put-get device
      
